const mongoose = require("mongoose");

const DefListSchema = new mongoose.Schema({
    title : { type: String, required: true, unique: true }, //For ex. Top Featured Drops
    type : { type: String }, //For ex. isPaid or not
    tags : { type: Array }, //For ex. AI, ML Modelling, etc
    drops: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Drop' }],
    isAutoGenerated: { type: Boolean, default: false },
},
    { timestamps: true },
);

module.exports = mongoose.model("Deflists", DefListSchema);