const cron = require('node-cron');
const Deflists = require('../../../models/Dropper/defaultLists');
const Drop = require('../../../models/Dropper/Drop');

cron.schedule('*/10 * * * *', async () => {  // Runs every 10 minutes
    console.log('Updating Newly Added Products list...');

    const latestDrops = await Drop.find().sort({ createdAt: -1 }).limit(10);

    await Deflists.findOneAndUpdate(
        { title: 'Newly Added Drops', isAutoGenerated: true },
        { drops: latestDrops.map(p => p._id) },
        { upsert: true } // Creates the list if it doesn't exist
    );

    console.log('Newly Added Products list updated.');
});