const router = require("express").Router();
const Deflists = require('../../../models/Dropper/defaultLists');
const verify = require("../../../verifyToken");

router.get('/', verify, async (req, res) => {
  try {
    const list = await Deflists.findOne({ title: 'Newly Added Drops', isAutoGenerated: true }).populate('drops');
    res.json(list ? list.drops : []);
  }catch(err){
    res.status(500).json(err);
  }
});

module.exports = router;
